development:
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: 123456
  database: i4_development

test:
  adapter: postgresql
  host: localhost
  port: 5432
  username: postgres
  password: 123456
  database: i4_test

production:
  adapter: postgresql
  username: postgres
  password: 123456
  database: i4_production
